sortable dependency
oxford-pharmacoepi/omopViewer pull request #70
Opened 2024-09-24 12:47 UTC by edward-burn

closes #66

2024-09-24 13:31 UTC, edward-burn commented
@catalamarti I updated the snapshots to try and get this passing, but am unsure why it caused such a large change in this

2024-09-25 09:42 UTC, catalamarti requested changes

2024-09-25 09:42 UTC, catalamarti commented on data-raw/internalData.R
> +  "library(sortable)",
delete

2024-09-25 13:36 UTC, catalamarti approved these changes

2024-09-25 13:36 UTC, catalamarti commented
thanks @edward-burn

2024-09-25 13:36 UTC, merged